Repository IBM/ibm-ingress-nginx-operator, pull requests merged in 2020-07, with the labels that each got.

#48 add replicas field
  deploy/crds/operator.ibm.com_v1alpha1_nginxingress_cr.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.3.0/ibm-ingress-nginx-operator.v1.3.0.clusterserviceversion.yaml
  helm-charts/nginx-ingress/templates/default-backend-deployment.yaml
  helm-charts/nginx-ingress/templates/ingress-deployment.yaml
  helm-charts/nginx-ingress/values-metadata.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: size/S

#49 New CSV 1.2.3 for CS 3.4 fix3
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.3/ibm-ingress-nginx-operator.v1.2.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.3/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
Labels: size/L

#50 Update image of operand nginx-ingress-controller
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.3/ibm-ingress-nginx-operator.v1.2.3.clusterserviceversion.yaml
Labels: size/XS

#51 upgrade helm operator base image to fix vulnerability issue
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/XS

#52 Revert "upgrade helm operator base image to fix vulnerability issue"
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/XS

#53 push 1.2.3 to stable v1
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
Labels: approved, size/XS
