Repository IBM/ibm-ingress-nginx-operator, pull requests merged in 2020-10, with the labels that each got.

#69 fix failing prow jobs.
  Makefile
  README.md
  build/Dockerfile-amd64
  build/Dockerfile-ppc64le
  build/Dockerfile-s390x
  common/Makefile.common.mk
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.0/ibm-ingress-nginx-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.1/ibm-ingress-nginx-operator.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.2/ibm-ingress-nginx-operator.v1.2.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.3/ibm-ingress-nginx-operator.v1.2.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.3.0/ibm-ingress-nginx-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.3.1/ibm-ingress-nginx-operator.v1.3.1.clusterserviceversion.yaml
  helm-charts/nginx-ingress/Chart.yaml
  helm-charts/nginx-ingress/README.md
  helm-charts/nginx-ingress/RELEASENOTES.md
Labels: approved, lgtm, size/L

#71 fix incorrect image and tag from multiarch image build.
  Makefile
Labels: approved, lgtm, size/XS

#72 fix incorrect image name for multiarch image build.
  Makefile
Labels: approved, lgtm, size/XS

#73 login before multiarch image build.
  Makefile
Labels: approved, lgtm, size/XS

#74 fix image arch suffix issue.
  Makefile
Labels: approved, lgtm, size/XS

#70 use restricted scc.
  Makefile
  README.md
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.3.2/ibm-ingress-nginx-operator.v1.3.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.3.2/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  helm-charts/nginx-ingress/README.md
  helm-charts/nginx-ingress/templates/ingress-deployment.yaml
  helm-charts/nginx-ingress/templates/ingress-service.yaml
  helm-charts/nginx-ingress/templates/post-upgrade-job.yaml
  helm-charts/nginx-ingress/templates/pre-delete-job.yaml
  helm-charts/nginx-ingress/templates/scc.yaml
  helm-charts/nginx-ingress/templates/script-configmap.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, lgtm, size/XL

#55 Optimize the permission for management-ingress operator and operand.
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.3.2/ibm-ingress-nginx-operator.v1.3.2.clusterserviceversion.yaml
  helm-charts/nginx-ingress/templates/ingress-deployment.yaml
  helm-charts/nginx-ingress/templates/rbac.yaml
  helm-charts/nginx-ingress/values.yaml
  watches.yaml
Labels: approved, lgtm, size/L

#75 fix version.
  Makefile
  common/Makefile.common.mk
  helm-charts/nginx-ingress/Chart.yaml
  version/version.go
Labels: approved, lgtm, size/S

#76 revert service port.
  helm-charts/nginx-ingress/README.md
  helm-charts/nginx-ingress/templates/ingress-service.yaml
  helm-charts/nginx-ingress/templates/script-configmap.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, lgtm, size/S

#77 updates the minor version.
  Makefile
  README.md
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.0/ibm-ingress-nginx-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.0/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  helm-charts/nginx-ingress/Chart.yaml
  version/version.go
Labels: approved, lgtm, size/S

#78 fix inconsistent user.
  helm-charts/nginx-ingress/templates/post-upgrade-job.yaml
  helm-charts/nginx-ingress/templates/pre-delete-job.yaml
Labels: approved, lgtm, size/XS

#79 fix issue of multiple watch namespaces separated by comma can't pass down to operand.
  helm-charts/nginx-ingress/templates/ingress-deployment.yaml
  helm-charts/nginx-ingress/values.yaml
  watches.yaml
Labels: approved, lgtm, size/S

#80 fix incorrect path.
  helm-charts/nginx-ingress/templates/ingress-deployment.yaml
Labels: approved, lgtm, size/XS

#81 update operand image digest.
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.0/ibm-ingress-nginx-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, lgtm, size/XS

#82 Remove post install hook
  Makefile
  build/Dockerfile
  build/Dockerfile-ppc64le
  build/Dockerfile-s390x
  deploy/clusterrole.yaml
  deploy/clusterrole_binding.yaml
  deploy/crds/operator.ibm.com_v1alpha1_nginxingress_cr.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.0/ibm-ingress-nginx-operator.v1.4.0.clusterserviceversion.yaml
  deploy/service_account.yaml
  helm-charts/nginx-ingress/templates/ingress-service.yaml
  helm-charts/nginx-ingress/templates/post-upgrade-job.yaml
  helm-charts/nginx-ingress/templates/pre-delete-job.yaml
  helm-charts/nginx-ingress/templates/route-configmap.yaml
  helm-charts/nginx-ingress/templates/script-configmap.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, lgtm, size/XL

#83 update csv.
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.0/ibm-ingress-nginx-operator.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#84 update operand image digest.
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.0/ibm-ingress-nginx-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, lgtm, size/XS
