Repository IBM/ibm-ingress-nginx-operator, pull requests merged in 2020-04, with the labels that each got.

#18 update version
  helm-charts/nginx-ingress/Chart.yaml
Labels: size/XS

#17 Change priority of scc to the lowest
  helm-charts/nginx-ingress/templates/scc.yaml
Labels: needs-ok-to-test, size/XS

#19 delete replace version
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.1.0/ibm-ingress-nginx-operator.v1.1.0.clusterserviceversion.yaml
Labels: size/XS

#20 update csv version
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.0/ibm-ingress-nginx-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.0/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  helm-charts/nginx-ingress/Chart.yaml
Labels: size/L

#21 add push csv script
  common/scripts/push-csv.sh
Labels: size/M

#22 add replace version
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.0/ibm-ingress-nginx-operator.v1.2.0.clusterserviceversion.yaml
Labels: size/XS

#23 push csv
  Makefile
  deploy/operator.yaml
Labels: size/XS

#24 update resource limit
  deploy/crds/operator.ibm.com_v1alpha1_nginxingress_cr.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.1.0/ibm-ingress-nginx-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.0/ibm-ingress-nginx-operator.v1.2.0.clusterserviceversion.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: size/XS
