Repository IBM/ibm-ingress-nginx-operator, pull requests merged in 2020-05, with the labels that each got.

#25 update base image
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/XS

#26 upadte base image
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/XS

#27 update base image
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/XS

#28 upadte cs version
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.0/ibm-ingress-nginx-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/templates/default-backend-deployment.yaml
  helm-charts/nginx-ingress/templates/ingress-deployment.yaml
Labels: size/XS

#29 Create or patch configmap ibmcloud-cluster-info to add proxy_address
  helm-charts/nginx-ingress/templates/script-configmap.yaml
Labels: size/S

#30 push latest image
  Makefile
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.0/ibm-ingress-nginx-operator.v1.2.0.clusterserviceversion.yaml
Labels: size/XS

#31 push latest image
  Makefile
Labels: size/XS

#32 Fix issue batch job failed to patch configmap
  helm-charts/nginx-ingress/templates/rbac.yaml
Labels: needs-ok-to-test, size/S

#34 update resource limit
  deploy/crds/operator.ibm.com_v1alpha1_nginxingress_cr.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.0/ibm-ingress-nginx-operator.v1.2.0.clusterserviceversion.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: size/XS

#35 update label
  helm-charts/nginx-ingress/templates/ingress-deployment.yaml
Labels: size/XS

#36 Update image version for 2020 Q2 release
  deploy/crds/operator.ibm.com_v1alpha1_nginxingress_cr.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.0/ibm-ingress-nginx-operator.v1.2.0.clusterserviceversion.yaml
  helm-charts/nginx-ingress/Chart.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: needs-ok-to-test, size/S

#37 Fix upgrade issue no enough permission
  deploy/clusterrole.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.0/ibm-ingress-nginx-operator.v1.2.0.clusterserviceversion.yaml
Labels: needs-ok-to-test, size/XS

#33 update readme
  README.md
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.0/ibm-ingress-nginx-operator.v1.2.0.clusterserviceversion.yaml
  helm-charts/nginx-ingress/templates/.script-configmap.yaml.swp
Labels: size/L

#38 Create beta channel for Common Service 2020 2Q release
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.0/ibm-ingress-nginx-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
Labels: needs-ok-to-test, size/M

#40 update operator version to 1.2.1
  Makefile
  README.md
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.1/ibm-ingress-nginx-operator.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.1/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  helm-charts/nginx-ingress/Chart.yaml
Labels: size/L

#39 fix operator upgrade issue and add the pre-delete hook to delete the cp-proxy
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.1/ibm-ingress-nginx-operator.v1.2.1.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/templates/.script-configmap.yaml.swp
  helm-charts/nginx-ingress/templates/default-backend-deployment.yaml
  helm-charts/nginx-ingress/templates/default-backend-service.yaml
  helm-charts/nginx-ingress/templates/ingress-configmap.yaml
  helm-charts/nginx-ingress/templates/ingress-deployment.yaml
  helm-charts/nginx-ingress/templates/ingress-service.yaml
  helm-charts/nginx-ingress/templates/post-upgrade-job.yaml
  helm-charts/nginx-ingress/templates/pre-delete-job.yaml
  helm-charts/nginx-ingress/templates/route-configmap.yaml
  helm-charts/nginx-ingress/templates/script-configmap.yaml
  helm-charts/nginx-ingress/templates/tests/test-nginx-ingress.yaml
  helm-charts/nginx-ingress/values.yaml
  watches.yaml
Labels: size/L

#42 Fix issue routeHost in CR does not take effect
  helm-charts/nginx-ingress/templates/post-upgrade-job.yaml
  helm-charts/nginx-ingress/templates/script-configmap.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: needs-ok-to-test, size/S

#43 Fix issue specified routeHost does not take effect
  deploy/crds/operator.ibm.com_v1alpha1_nginxingress_cr.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.2.1/ibm-ingress-nginx-operator.v1.2.1.clusterserviceversion.yaml
  helm-charts/nginx-ingress/templates/post-upgrade-job.yaml
  helm-charts/nginx-ingress/templates/script-configmap.yaml
Labels: needs-ok-to-test, size/S
