Repository IBM/ibm-ingress-nginx-operator, pull requests merged in 2020-11, with the labels that each got.

#85 support namespace scope operator.
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.0/ibm-ingress-nginx-operator.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#86 update operand image digest.
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.0/ibm-ingress-nginx-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, lgtm, size/XS

#87 update operand image digest.
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.0/ibm-ingress-nginx-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, lgtm

#88 add project label to operand.
  helm-charts/nginx-ingress/templates/ingress-deployment.yaml
Labels: approved, lgtm, size/XS

#89 fix serviceaccount not present issue during upgrade.
  README.md
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.0/ibm-ingress-nginx-operator.v1.4.0.clusterserviceversion.yaml
  helm-charts/nginx-ingress/templates/default-backend-deployment.yaml
  helm-charts/nginx-ingress/templates/ingress-deployment.yaml
  helm-charts/nginx-ingress/templates/ingress-service.yaml
Labels: approved, lgtm, size/S

#90 fix service account not present issue during upgrade.
  helm-charts/nginx-ingress/templates/ingress-deployment.yaml
Labels: approved, size/XS

#91 update base image.
  build/Dockerfile
  build/Dockerfile-ppc64le
  build/Dockerfile-s390x
Labels: approved, lgtm, size/XS

#92 upgrade version.
  Makefile
  README.md
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.1/ibm-ingress-nginx-operator.v1.4.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.1/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  helm-charts/nginx-ingress/Chart.yaml
  version/version.go
Labels: approved, lgtm, size/L

#93 fix multiarch image manifests.
  Makefile
Labels: approved, lgtm, size/XS

#94 bump new version.
  Makefile
  README.md
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.2/ibm-ingress-nginx-operator.v1.4.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.2/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  helm-charts/nginx-ingress/Chart.yaml
  version/version.go
Labels: approved, lgtm, size/L

#95 update operand image digest.
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.2/ibm-ingress-nginx-operator.v1.4.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#96 Revert back change about bump up to version 1.4.2
  Makefile
  README.md
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.1/ibm-ingress-nginx-operator.v1.4.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.2/ibm-ingress-nginx-operator.v1.4.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.2/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  helm-charts/nginx-ingress/Chart.yaml
  version/version.go
Labels: approved, lgtm, size/L

#97 bring back the kubectl and icp-initcontainer image and update digests.
  deploy/crds/operator.ibm.com_v1alpha1_nginxingress_cr.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.1/ibm-ingress-nginx-operator.v1.4.1.clusterserviceversion.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, size/M

#98 fix service account not present during upgrade.
  helm-charts/nginx-ingress/templates/default-backend-deployment.yaml
Labels: approved, size/XS
