Repository IBM/ibm-ingress-nginx-operator, pull requests merged in 2020-03, with the labels that each got.

#5 Bump ingress nginx controller image version
  deploy/crds/operator.ibm.com_v1alpha1_nginxingress_cr.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/0.0.1/ibm-ingress-nginx-operator.v0.0.1.clusterserviceversion.yaml
  helm-charts/nginx-ingress/README.md
  helm-charts/nginx-ingress/RELEASENOTES.md
  helm-charts/nginx-ingress/ibm_cloud_pak/manifest.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: needs-ok-to-test, size/S

#6 Auto discover route host
  Makefile
  build/Dockerfile.s390x
  deploy/clusterrole.yaml
  deploy/crds/operator.ibm.com_v1alpha1_nginxingress_cr.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/0.0.1/ibm-ingress-nginx-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  helm-charts/nginx-ingress/templates/ingress-route.yaml
  helm-charts/nginx-ingress/templates/job.yaml
  helm-charts/nginx-ingress/templates/rbac.yaml
  helm-charts/nginx-ingress/templates/route-configmap.yaml
  helm-charts/nginx-ingress/templates/scc.yaml
  helm-charts/nginx-ingress/templates/script-configmap.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: needs-ok-to-test, size/XL

#7 Delete route route first before create new one
  helm-charts/nginx-ingress/templates/script-configmap.yaml
Labels: needs-ok-to-test, size/XS

#8 add labels for operator image to pass the UBI image certification
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/M

#9 Add resource limits for the operand pod
  deploy/crds/operator.ibm.com_v1alpha1_nginxingress_cr.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/0.0.1/ibm-ingress-nginx-operator.v0.0.1.clusterserviceversion.yaml
  helm-charts/nginx-ingress/templates/job.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: needs-ok-to-test, size/S

#10 change user for adding license
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/XS

#11 Revert "change user for adding license"
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/XS

#12 change root user for adding license
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/XS

#14 Add resource limit and annotation for operator itself
  deploy/crds/operator.ibm.com_v1alpha1_nginxingress_cr.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.1.0/ibm-ingress-nginx-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.1.0/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/templates/ingress-deployment.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: needs-ok-to-test, size/M

#16 Adjust resource limit for the ingress job
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/crds/operator.ibm.com_v1alpha1_nginxingress_cr.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.1.0/ibm-ingress-nginx-operator.v1.1.0.clusterserviceversion.yaml
  helm-charts/nginx-ingress/templates/job.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: needs-ok-to-test, size/M
