Repository IBM/ibm-ingress-nginx-operator, pull requests merged in 2021-11, with the labels that each got.

#147 Release eus
  Makefile
  README.md
  build/Dockerfile
  build/Dockerfile-ppc64le
  build/Dockerfile-s390x
  common/scripts/bump-up-csv.sh
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.4/ibm-ingress-nginx-operator.v1.4.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.4/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  helm-charts/nginx-ingress/Chart.yaml
  version/version.go
Labels: size/L, approved

#148 bump up version
  README.md
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.11.0/ibm-ingress-nginx-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.11.0/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
Labels: size/L, approved

#151 Update helm operator image for eus
  build/Dockerfile
  build/Dockerfile-ppc64le
  build/Dockerfile-s390x
Labels: size/XS, approved

#150 Udate helm operator image to latest
  build/Dockerfile
  build/Dockerfile-ppc64le
  build/Dockerfile-s390x
Labels: size/XS, approved

#152 update version
  version/version.go
Labels: approved

#153 update
  helm-charts/nginx-ingress/Chart.yaml
Labels: approved

#154 Revert "bump up version"
  README.md
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.11.0/ibm-ingress-nginx-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.11.0/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
Labels: size/L, approved

#155 bump up version from 1.10.0
  Makefile
  README.md
  common/scripts/bump-up-csv.sh
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.11.0/ibm-ingress-nginx-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.11.0/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
Labels: size/L, approved

#159 Bump helm operator image for eus
  build/Dockerfile
  build/Dockerfile-ppc64le
  build/Dockerfile-s390x
Labels: size/XS

#158 Bump helm operator image to latest
  build/Dockerfile
  build/Dockerfile-ppc64le
  build/Dockerfile-s390x
Labels: size/XS, approved

#157 Changes for RH mirroring for eus
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.4/ibm-ingress-nginx-operator.v1.4.4.clusterserviceversion.yaml
Labels: size/XS

#156 Changes for RH Mirroring
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.11.0/ibm-ingress-nginx-operator.v1.11.0.clusterserviceversion.yaml
Labels: size/XS
