Repository IBM/ibm-ingress-nginx-operator, pull requests merged in 2021-06, with the labels that each got.

#121 update sha for default-http-backend
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.6.0/ibm-ingress-nginx-operator.v1.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, size/XS

#122 update sha for kubectl
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.6.0/ibm-ingress-nginx-operator.v1.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, size/XS

#125 update sha values for ingress-nginx-controller
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.6.0/ibm-ingress-nginx-operator.v1.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, size/XS

#126 update base image to v1.8.0 for p and z
  build/Dockerfile-ppc64le
  build/Dockerfile-s390x
Labels: approved, size/XS

#127 Update sha for operands
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.6.0/ibm-ingress-nginx-operator.v1.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, size/S

#129 bump up csv
  Makefile
  README.md
  common/scripts/bump-up-csv.sh
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.7.0/ibm-ingress-nginx-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.7.0/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  helm-charts/nginx-ingress/Chart.yaml
  version/version.go
Labels: approved, size/L

#130 Changes for 46828: Setting resource requests and limits in the CSV
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.7.0/ibm-ingress-nginx-operator.v1.7.0.clusterserviceversion.yaml
Labels: approved, size/XS

#131 Release cd
  Makefile
  README.md
  common/scripts/bump-up-csv.sh
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.7.0/ibm-ingress-nginx-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.7.0/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  helm-charts/nginx-ingress/Chart.yaml
  version/version.go
Labels: approved, size/L

#132 operands sha auto update
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.7.0/ibm-ingress-nginx-operator.v1.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  watches.yaml
Labels: approved, size/M

#133 update memory request and limit for ingress nginx operator
  build/Dockerfile-ppc64le
  build/Dockerfile-s390x
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.7.0/ibm-ingress-nginx-operator.v1.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#134 v1beta1 -> v1
  deploy/crds/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.7.0/ibm-ingress-nginx-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.7.0/operator.ibm.com_nginxingresses_crd.yaml
Labels: approved, size/M

#135 update crd
  deploy/crds/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.7.0/operator.ibm.com_nginxingresses_crd.yaml
Labels: approved, size/XS
