Repository IBM/ibm-ingress-nginx-operator, pull requests merged in 2021-12, with the labels that each got.

#160 Operand auto sha update
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.4/ibm-ingress-nginx-operator.v1.4.4.clusterserviceversion.yaml
  deploy/operator.yaml
  watches.yaml
Labels: size/M, approved

#162 Bump up version
  Makefile
  README.md
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.12.0/ibm-ingress-nginx-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.12.0/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  helm-charts/nginx-ingress/Chart.yaml
  version/version.go
Labels: size/L, lgtm, approved

#161 Delete codecov.io reference
  Makefile
  common/scripts/codecov.sh
Labels: size/XS, approved, security
