Repository IBM/ibm-ingress-nginx-operator, pull requests merged in 2021-05, with the labels that each got.

#112 bump up version to 1.4.3 for CS 3.6.5
  Makefile
  OWNERS
  README.md
  common/scripts/bump-up-csv.sh
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.3/ibm-ingress-nginx-operator.v1.4.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.3/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/Chart.yaml
  helm-charts/nginx-ingress/values.yaml
  version/version.go
Labels: size/XL

#113 bump up version to 1.6.0 for CS 3.8
  Makefile
  OWNERS
  README.md
  common/scripts/bump-up-csv.sh
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.6.0/ibm-ingress-nginx-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.6.0/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/Chart.yaml
  helm-charts/nginx-ingress/values.yaml
  version/version.go
Labels: approved, size/XL

#114 update SHA for operands
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.4.3/ibm-ingress-nginx-operator.v1.4.3.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: size/S

#117 update SHA for operands
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.6.0/ibm-ingress-nginx-operator.v1.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, size/XS

#118 add pod topology constraint
  helm-charts/nginx-ingress/templates/default-backend-deployment.yaml
  helm-charts/nginx-ingress/templates/ingress-deployment.yaml
Labels: approved, lgtm, size/M

#119 update SHA
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.6.0/ibm-ingress-nginx-operator.v1.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, size/S

#120 update sha
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.6.0/ibm-ingress-nginx-operator.v1.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: approved, size/XS
