Repository IBM/ibm-ingress-nginx-operator, pull requests merged in 2022-03, with the labels that each got.

#166 cs 3.17 bump version
  Makefile
  README.md
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.14.0/ibm-ingress-nginx-operator.v1.14.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.14.0/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/Chart.yaml
  version/version.go
Labels: size/L

#167 trigger build
  OWNERS
  README.md
Labels: size/S

#168 opt in for auto updates for the helm operator image
  Makefile
  base_images.json
  build/Dockerfile
  build/Dockerfile-ppc64le
  build/Dockerfile-s390x
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: lgtm, size/S, approved
