Repository IBM/ibm-ingress-nginx-operator, pull requests merged in 2022-04, with the labels that each got.

#169 version bump april
  Makefile
  README.md
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.15.0/ibm-ingress-nginx-operator.v1.15.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.15.0/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/Chart.yaml
  version/version.go
Labels: size/L, lgtm, approved

#170 remove csv replaces keyword for LTSR
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.15.0/ibm-ingress-nginx-operator.v1.15.0.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#171 update image refs to use icr
  common/config/.hadolint.yml
  deploy/crds/operator.ibm.com_v1alpha1_nginxingress_cr.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.15.0/ibm-ingress-nginx-operator.v1.15.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/values-metadata.yaml
  helm-charts/nginx-ingress/values.yaml
Labels: lgtm, size/M, approved
