Repository IBM/ibm-ingress-nginx-operator, pull requests merged in 2022-11, with the labels that each got.

#195 vbump to 1.16.7/CS 3.19.7
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.16.7/ibm-ingress-nginx-operator.v1.16.7.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.16.7/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  deploy/operator.yaml
  helm-charts/nginx-ingress/Chart.yaml
  version/version.go
Labels: size/L, lgtm, approved

#196 test prow trigger
  common/Makefile.common.mk
  triggerfile
Labels: lgtm, size/XS

#197 Test prow updates
  triggerfile
Labels: size/XS

#198 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#199 version bump 1.20.0/3.22.0
  README.md
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.20.0/ibm-ingress-nginx-operator.v1.20.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/1.20.0/operator.ibm.com_nginxingresses_crd.yaml
  deploy/olm-catalog/ibm-ingress-nginx-operator/ibm-ingress-nginx-operator.package.yaml
  helm-charts/nginx-ingress/Chart.yaml
  version/version.go
Labels: size/L, lgtm, approved
